#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "ptlzx", id = "d66bf7f5bf8a4e43b608ddf14a7ad824" }
]
